services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d6m3b9fgi27c73dsiqq0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ecommerce_p2q6
      - key: DB_USERNAME
        value: ecommerce_p2q6_user
      - key: DB_PASSWORD
        value:  raP6V0l5a3XjrS6mi7IVjhxrE6ArbgHf
        sync: false         
