services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d6m3b9fgi27c73dsiqq0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ecommerce_p2q6
      - key: DB_USERNAME
        value: ecommerce_p2q6_user
      - key: DB_PASSWORD
        value:  raP6V0l5a3XjrS6mi7IVjhxrE6ArbgHf
      - key: CLOUDINARY_KEY
        value: your-api-key
      - key: CLOUDINARY_SECRET
        value: your-api-secret
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloud-name
      - key: FILESYSTEM_DISK
        value: cloudinary
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: GOOGLE_REDIRECT_URI
        value: https://ecommerce-wdoj.onrender.com/auth/google/callback
        sync: false         
